############################################################################
#                                                                          #
#              SIMPLIFIED BUILDER FOR SERVICE TRAINING                     #
#                                                                          #
############################################################################

# This Cloud Build file builds a Docker image and pushes it to Artifact Registry.
#
# Usage:
#   gcloud builds submit --region=us-central1 --config=deploy/cloudbuild/cloudbuild-service-training.yaml


substitutions:
  _GOOGLE_CLOUD_PROJECT: "laxai-466119"
  #_SERVICE_ACCOUNT: "service-training@laxai-466119.iam.gserviceaccount.com"

steps:
  # Build the service training image
  - id: "build-service-training-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "GIT_COMMIT_SHA=${SHORT_SHA}"
      - "-f"
      - "services/service_training/Dockerfile"
      - "-t"
      - "us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-service-training:latest"
      - "."

  # Push the service training image
  - id: "push-service-training-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-service-training:latest"

  # Update the Cloud Run Job to use the latest image
  - id: "update-cloud-run-job"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "jobs"
      - "update"
      - "laxai-service-training"
      - "--region=us-central1"
      - "--image=us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-service-training:latest"

images:
  - "us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-service-training:latest"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "3600s"
